{ut: [
{
	"broj": 6998
,	"liga": 36
,	"ekipa1": 166
,	"ekipa2": 165
,	"datum": "1899-12-30"
,	"vrijeme": "00:00:00"
,	"status": 2
,	"r1": 27
,	"r2": 27
,	"mjesto": ""
,	"kolo": 17
,	reg1: null
,	reg2: null
,	neutralan: null
,	sluzbena: null
,	"p11": 9
,	"p12": 14
,	"p21": 18
,	"p22": 13
,	p31: null
,	p32: null
,	p41: null
,	p42: null
,	serija: null
,	sport: null
,	spol: null
,	izvjestaj: null
,	"trenutnistatus": 3
,	formatvremena: null
,	"period": 2
,	"minuta": 60
,	"sekundi": 0
,	"pocetakperioda": "1899-12-30T00:00:00"
,	"zadnjapromjena": "1899-12-30T00:00:00"
,	izvorrezultat: null
,	izvorizvjestaj: null
,	"pocetak": "2021-05-16T11:00:00"
,	p51: null
,	p52: null
,	importiskljucen: null
,	izvordv: null
,	prioritetdv: null
,	vremenskarazlika: null
,	"zadnjapromjenaeksport": "207671700"
,	"zadnjapromjenadetalja": ""
,	stadion: null
,	sudac1: null
,	sudac2: null
,	sudac3: null
,	"opis": ""
,	zdrijeb: null
,	izvorserijakolo: null
,	servis: null
,	turnir: null
,	"zavrsetak": "1899-12-30T00:00:00"
,	definiranasatnica: null
,	"tv": ""
,	sehalivestreaming: null
,	razlikacet: null
,	pdfseha: null
,	ukupnominuta: null
,	godiste1: null
,	godiste2: null
,	tecaj1: null
,	tecajx: null
,	tecaj2: null
,	marginazbroj: null
,	marginahendikep: null
,	statusnominacije: null
,	"statusvrijeme": 1
,	"rp_promjena": "207671700"
,	"rp_dodan": "845902"
,	rp_ostaviti: null
,	"mjestoodigravanja": 312
,	"opaske": ""
,	bezborbe: null
,	faza: null
,	zamjesto: null
,	leg: null
,	tecajzbrojunder: null
,	tecajzbrojover: null
,	ekipaorganizator: null
,	"bojad1": 2
,	bojad2: null
,	"bojag1": 0
,	bojag2: null
,	"bojagolmand1": 4
,	bojagolmand2: null
,	"bojagolmang1": 3
,	bojagolmang2: null
,	kluborganizator: null
,	"formatutakmicekod": ""
,	eksterniid: null
,	"promjenaprijedloga": "1899-12-30T00:00:00"
,	"opis1": ""
,	"opis2": ""
,	uvjetna: null
,	"n1": "Hoteli Makarska"
,	"k1": 1680
,	"n2": "MetkoviД‡"
,	"k2": 1684
,	"nn": "2.HRL Jug - ЕЅene"
,	"v1": 0
,	"v2": 0
,	"dr1": "hr"
,	"dr2": "hr"
}
]
, role: [
{
	"broj": 4038
,	"utakmica": 6998
,	"uredjaj": 567
,	"rola": 2
,	"datumvrijeme": "2021-05-16T11:00:00"
,	"dvorana": 312
,	"status": 3
,	"period": 1
,	"minuta": 60
,	odbrojavanjevremena: null
,	"sekundi": 0
,	"r1": 27
,	"r2": 27
,	"p11": 9
,	"p12": 14
,	"p21": 18
,	"p22": 13
,	p31: null
,	p32: null
,	p41: null
,	p42: null
,	p51: null
,	p52: null
,	pravila: null
,	golman1: null
,	golman2: null
,	obrana1: null
,	obrana2: null
,	"easistencija1": 0
,	"easistencija2": 0
,	"etehnickih1": 0
,	"etehnickih2": 0
,	"eosvojenih1": 0
,	"eosvojenih2": 0
,	"eiskljucenja1": 0
,	"eiskljucenja2": 0
,	"ezutih1": 0
,	"ezutih2": 0
,	"ecrvenih1": 0
,	"ecrvenih2": 0
,	"unesenisastavi": 1
,	"eizborenihiskljucenja1": 0
,	"eizborenihiskljucenja2": 0
,	"gledatelja": 0
,	brojutv: null
,	"vrijemeigraca": 1
,	"faza": "17. kolo"
,	"posjed1": 1835
,	"posjed2": 3565
,	"racunanjeposjeda": 1
,	napad1: null
,	napad2: null
,	starigolman1: null
,	starigolman2: null
,	"superiornost": 0
,	"kratica1": "Hoteli Makarska"
,	"kratica2": "MetkoviД‡"
,	"desetinki": 0
,	"statusunosa": 2
,	pasivna: null
,	prviperiodlijevo: null
,	"napada1": 28
,	"napada2": 26
,	"lokalid": 18
,	"rp_promjena": "207671698"
,	"rp_dodan": "207489788"
,	rp_ostaviti: null
,	"brojutvanjski": ""
,	"dodatnoslijedi": 0
,	"dodatnoizvjesce": ""
,	"verificirao": 119817
,	verficirano: null
,	"dvverifikacije": "2021-05-16T12:27:49"
,	"verificirano": 1
,	"glavna": 1
}
]
, sastavi: [
{
	"broj": 117200
,	"igrac": 124074
,	"ime": "Marijeta"
,	"prezime": "PrnjiД‡"
,	"dres": 1
,	"rbekipa": 2
,	"utakmica": 6998
,	"uredjaj": 567
,	"tipigraca": 0
,	"sutd": 0
,	"sutp": 0
,	"sutkrilod": 0
,	"sutkrilop": 0
,	"sutcrtad": 0
,	"sutcrtap": 0
,	"sutizvanad": 0
,	"sutizvanap": 0
,	"sutkontrad": 0
,	"sutkontrap": 0
,	"sutprolazd": 0
,	"sutprolazp": 0
,	"asistencija": 0
,	"tehnickih": 0
,	"osvojenih": 0
,	"iskljucenja": 0
,	"zutih": 0
,	"crvenih": 0
,	"skrivljenihsedmeraca": 0
,	"izborenihsedmeraca": 0
,	"obraned": 0
,	"obranep": 0
,	"obranekrilod": 0
,	"obranekrilop": 0
,	"obraneizvanad": 0
,	"obraneizvanap": 0
,	"obranekontrad": 0
,	"obranekontrap": 0
,	"obraneprolazd": 0
,	"obraneprolazp": 0
,	"sutsedmeracd": 0
,	"sutsedmeracp": 0
,	"obranesedmeracd": 0
,	"obranesedmeracp": 0
,	"obranecrtap": 0
,	"obranecrtad": 0
,	"izborenihiskljucenja": 0
,	"blokova": 0
,	"asistencijacepelin": 0
,	"bodova": 0
,	sekundi: null
,	"valigrac": 0
,	"valgolman": 0
,	rezefekt: null
,	"sutizdalekad": 0
,	"sutizdalekap": 0
,	"obraneizdalekad": 0
,	"obraneizdalekap": 0
,	starter: null
,	"plavih": 0
,	"pasova": 0
,	nagrada: null
,	"ekipa": 165
,	"lokalid": 509
,	"lokalutakmica": 18
,	"rp_promjena": "207591050"
,	"rp_dodan": "207489870"
,	rp_ostaviti: null
,	"i": "Marijeta"
,	"p": "PrnjiД‡"
,	"sl": ""
,	pz: null
}
, {
	"broj": 117197
,	"igrac": 122980
,	"ime": "Laura"
,	"prezime": "MajiД‡"
,	"dres": 2
,	"rbekipa": 2
,	"utakmica": 6998
,	"uredjaj": 567
,	"tipigraca": 0
,	"sutd": 0
,	"sutp": 0
,	"sutkrilod": 0
,	"sutkrilop": 0
,	"sutcrtad": 0
,	"sutcrtap": 0
,	"sutizvanad": 0
,	"sutizvanap": 0
,	"sutkontrad": 0
,	"sutkontrap": 0
,	"sutprolazd": 0
,	"sutprolazp": 0
,	"asistencija": 0
,	"tehnickih": 0
,	"osvojenih": 0
,	"iskljucenja": 0
,	"zutih": 0
,	"crvenih": 0
,	"skrivljenihsedmeraca": 0
,	"izborenihsedmeraca": 0
,	"obraned": 0
,	"obranep": 0
,	"obranekrilod": 0
,	"obranekrilop": 0
,	"obraneizvanad": 0
,	"obraneizvanap": 0
,	"obranekontrad": 0
,	"obranekontrap": 0
,	"obraneprolazd": 0
,	"obraneprolazp": 0
,	"sutsedmeracd": 0
,	"sutsedmeracp": 0
,	"obranesedmeracd": 0
,	"obranesedmeracp": 0
,	"obranecrtap": 0
,	"obranecrtad": 0
,	"izborenihiskljucenja": 0
,	"blokova": 0
,	"asistencijacepelin": 0
,	"bodova": 0
,	sekundi: null
,	"valigrac": 0
,	"valgolman": 0
,	rezefekt: null
,	"sutizdalekad": 0
,	"sutizdalekap": 0
,	"obraneizdalekad": 0
,	"obraneizdalekap": 0
,	starter: null
,	"plavih": 0
,	"pasova": 0
,	nagrada: null
,	"ekipa": 165
,	"lokalid": 506
,	"lokalutakmica": 18
,	"rp_promjena": "207591044"
,	"rp_dodan": "207489864"
,	rp_ostaviti: null
,	"i": "Laura"
,	"p": "MajiД‡"
,	"sl": ""
,	pz: null
}
, {
	"broj": 117180
,	"igrac": 127856
,	"ime": "Mia"
,	"prezime": "Bandur"
,	"dres": 4
,	"rbekipa": 1
,	"utakmica": 6998
,	"uredjaj": 567
,	"tipigraca": 0
,	"sutd": 8
,	"sutp": 8
,	"sutkrilod": 8
,	"sutkrilop": 8
,	"sutcrtad": 0
,	"sutcrtap": 0
,	"sutizvanad": 0
,	"sutizvanap": 0
,	"sutkontrad": 0
,	"sutkontrap": 0
,	"sutprolazd": 0
,	"sutprolazp": 0
,	"asistencija": 0
,	"tehnickih": 0
,	"osvojenih": 0
,	"iskljucenja": 1
,	"zutih": 0
,	"crvenih": 0
,	"skrivljenihsedmeraca": 0
,	"izborenihsedmeraca": 0
,	"obraned": 0
,	"obranep": 0
,	"obranekrilod": 0
,	"obranekrilop": 0
,	"obraneizvanad": 0
,	"obraneizvanap": 0
,	"obranekontrad": 0
,	"obranekontrap": 0
,	"obraneprolazd": 0
,	"obraneprolazp": 0
,	"sutsedmeracd": 0
,	"sutsedmeracp": 0
,	"obranesedmeracd": 0
,	"obranesedmeracp": 0
,	"obranecrtap": 0
,	"obranecrtad": 0
,	"izborenihiskljucenja": 0
,	"blokova": 0
,	"asistencijacepelin": 0
,	"bodova": 0
,	sekundi: null
,	"valigrac": 6.5
,	"valgolman": 6.5
,	rezefekt: null
,	"sutizdalekad": 0
,	"sutizdalekap": 0
,	"obraneizdalekad": 0
,	"obraneizdalekap": 0
,	starter: null
,	"plavih": 0
,	"pasova": 0
,	nagrada: null
,	"ekipa": 166
,	"lokalid": 489
,	"lokalutakmica": 18
,	"rp_promjena": "207653012"
,	"rp_dodan": "207489818"
,	rp_ostaviti: null
,	"i": "Mia"
,	"p": "Bandur"
,	"sl": ""
,	pz: null
}
, {
	"broj": 117199
,	"igrac": 123634
,	"ime": "Petra"
,	"prezime": "ObЕЎivaДЌ"
,	"dres": 5
,	"rbekipa": 2
,	"utakmica": 6998
,	"uredjaj": 567
,	"tipigraca": 0
,	"sutd": 7
,	"sutp": 7
,	"sutkrilod": 7
,	"sutkrilop": 7
,	"sutcrtad": 0
,	"sutcrtap": 0
,	"sutizvanad": 0
,	"sutizvanap": 0
,	"sutkontrad": 0
,	"sutkontrap": 0
,	"sutprolazd": 0
,	"sutprolazp": 0
,	"asistencija": 0
,	"tehnickih": 0
,	"osvojenih": 0
,	"iskljucenja": 0
,	"zutih": 0
,	"crvenih": 0
,	"skrivljenihsedmeraca": 0
,	"izborenihsedmeraca": 0
,	"obraned": 0
,	"obranep": 0
,	"obranekrilod": 0
,	"obranekrilop": 0
,	"obraneizvanad": 0
,	"obraneizvanap": 0
,	"obranekontrad": 0
,	"obranekontrap": 0
,	"obraneprolazd": 0
,	"obraneprolazp": 0
,	"sutsedmeracd": 0
,	"sutsedmeracp": 0
,	"obranesedmeracd": 0
,	"obranesedmeracp": 0
,	"obranecrtap": 0
,	"obranecrtad": 0
,	"izborenihiskljucenja": 0
,	"blokova": 0
,	"asistencijacepelin": 0
,	"bodova": 0
,	sekundi: null
,	"valigrac": 7
,	"valgolman": 7
,	rezefekt: null
,	"sutizdalekad": 0
,	"sutizdalekap": 0
,	"obraneizdalekad": 0
,	"obraneizdalekap": 0
,	starter: null
,	"plavih": 0
,	"pasova": 0
,	nagrada: null
,	"ekipa": 165
,	"lokalid": 508
,	"lokalutakmica": 18
,	"rp_promjena": "207652618"
,	"rp_dodan": "207489868"
,	rp_ostaviti: null
,	"i": "Petra"
,	"p": "ObЕЎivaДЌ"
,	"sl": ""
,	pz: null
}
, {
	"broj": 117194
,	"igrac": 121484
,	"ime": "Lea"
,	"prezime": "Erceg"
,	"dres": 6
,	"rbekipa": 2
,	"utakmica": 6998
,	"uredjaj": 567
,	"tipigraca": 0
,	"sutd": 0
,	"sutp": 0
,	"sutkrilod": 0
,	"sutkrilop": 0
,	"sutcrtad": 0
,	"sutcrtap": 0
,	"sutizvanad": 0
,	"sutizvanap": 0
,	"sutkontrad": 0
,	"sutkontrap": 0
,	"sutprolazd": 0
,	"sutprolazp": 0
,	"asistencija": 0
,	"tehnickih": 0
,	"osvojenih": 0
,	"iskljucenja": 0
,	"zutih": 0
,	"crvenih": 0
,	"skrivljenihsedmeraca": 0
,	"izborenihsedmeraca": 0
,	"obraned": 0
,	"obranep": 0
,	"obranekrilod": 0
,	"obranekrilop": 0
,	"obraneizvanad": 0
,	"obraneizvanap": 0
,	"obranekontrad": 0
,	"obranekontrap": 0
,	"obraneprolazd": 0
,	"obraneprolazp": 0
,	"sutsedmeracd": 0
,	"sutsedmeracp": 0
,	"obranesedmeracd": 0
,	"obranesedmeracp": 0
,	"obranecrtap": 0
,	"obranecrtad": 0
,	"izborenihiskljucenja": 0
,	"blokova": 0
,	"asistencijacepelin": 0
,	"bodova": 0
,	sekundi: null
,	"valigrac": 0
,	"valgolman": 0
,	rezefekt: null
,	"sutizdalekad": 0
,	"sutizdalekap": 0
,	"obraneizdalekad": 0
,	"obraneizdalekap": 0
,	starter: null
,	"plavih": 0
,	"pasova": 0
,	nagrada: null
,	"ekipa": 165
,	"lokalid": 503
,	"lokalutakmica": 18
,	"rp_promjena": "207591032"
,	"rp_dodan": "207489858"
,	rp_ostaviti: null
,	"i": "Lea"
,	"p": "Erceg"
,	"sl": ""
,	pz: null
}
, {
	"broj": 117189
,	"igrac": 134559
,	"ime": "Danijela"
,	"prezime": "VujДЌiД‡"
,	"dres": 6
,	"rbekipa": 1
,	"utakmica": 6998
,	"uredjaj": 567
,	"tipigraca": 0
,	"sutd": 1
,	"sutp": 1
,	"sutkrilod": 1
,	"sutkrilop": 1
,	"sutcrtad": 0
,	"sutcrtap": 0
,	"sutizvanad": 0
,	"sutizvanap": 0
,	"sutkontrad": 0
,	"sutkontrap": 0
,	"sutprolazd": 0
,	"sutprolazp": 0
,	"asistencija": 0
,	"tehnickih": 0
,	"osvojenih": 0
,	"iskljucenja": 0
,	"zutih": 0
,	"crvenih": 0
,	"skrivljenihsedmeraca": 0
,	"izborenihsedmeraca": 0
,	"obraned": 0
,	"obranep": 0
,	"obranekrilod": 0
,	"obranekrilop": 0
,	"obraneizvanad": 0
,	"obraneizvanap": 0
,	"obranekontrad": 0
,	"obranekontrap": 0
,	"obraneprolazd": 0
,	"obraneprolazp": 0
,	"sutsedmeracd": 0
,	"sutsedmeracp": 0
,	"obranesedmeracd": 0
,	"obranesedmeracp": 0
,	"obranecrtap": 0
,	"obranecrtad": 0
,	"izborenihiskljucenja": 0
,	"blokova": 0
,	"asistencijacepelin": 0
,	"bodova": 0
,	sekundi: null
,	"valigrac": 1
,	"valgolman": 1
,	rezefekt: null
,	"sutizdalekad": 0
,	"sutizdalekap": 0
,	"obraneizdalekad": 0
,	"obraneizdalekap": 0
,	starter: null
,	"plavih": 0
,	"pasova": 0
,	nagrada: null
,	"ekipa": 166
,	"lokalid": 498
,	"lokalutakmica": 18
,	"rp_promjena": "207651572"
,	"rp_dodan": "207489836"
,	rp_ostaviti: null
,	"i": "Danijela"
,	"p": "VujДЌiД‡"
,	"sl": ""
,	pz: null
}
, {
	"broj": 117201
,	"igrac": 124525
,	"ime": "Antonela"
,	"prezime": "Srna"
,	"dres": 7
,	"rbekipa": 2
,	"utakmica": 6998
,	"uredjaj": 567
,	"tipigraca": 0
,	"sutd": 0
,	"sutp": 0
,	"sutkrilod": 0
,	"sutkrilop": 0
,	"sutcrtad": 0
,	"sutcrtap": 0
,	"sutizvanad": 0
,	"sutizvanap": 0
,	"sutkontrad": 0
,	"sutkontrap": 0
,	"sutprolazd": 0
,	"sutprolazp": 0
,	"asistencija": 0
,	"tehnickih": 0
,	"osvojenih": 0
,	"iskljucenja": 1
,	"zutih": 1
,	"crvenih": 0
,	"skrivljenihsedmeraca": 0
,	"izborenihsedmeraca": 0
,	"obraned": 0
,	"obranep": 0
,	"obranekrilod": 0
,	"obranekrilop": 0
,	"obraneizvanad": 0
,	"obraneizvanap": 0
,	"obranekontrad": 0
,	"obranekontrap": 0
,	"obraneprolazd": 0
,	"obraneprolazp": 0
,	"sutsedmeracd": 0
,	"sutsedmeracp": 0
,	"obranesedmeracd": 0
,	"obranesedmeracp": 0
,	"obranecrtap": 0
,	"obranecrtad": 0
,	"izborenihiskljucenja": 0
,	"blokova": 0
,	"asistencijacepelin": 0
,	"bodova": 0
,	sekundi: null
,	"valigrac": -1.5
,	"valgolman": -1.5
,	rezefekt: null
,	"sutizdalekad": 0
,	"sutizdalekap": 0
,	"obraneizdalekad": 0
,	"obraneizdalekap": 0
,	starter: null
,	"plavih": 0
,	"pasova": 0
,	nagrada: null
,	"ekipa": 165
,	"lokalid": 510
,	"lokalutakmica": 18
,	"rp_promjena": "207600686"
,	"rp_dodan": "207489872"
,	rp_ostaviti: null
,	"i": "Antonela"
,	"p": "Srna"
,	"sl": ""
,	pz: null
}
, {
	"broj": 117188
,	"igrac": 125239
,	"ime": "Victoria Eva"
,	"prezime": "VranjeЕЎ"
,	"dres": 7
,	"rbekipa": 1
,	"utakmica": 6998
,	"uredjaj": 567
,	"tipigraca": 0
,	"sutd": 5
,	"sutp": 5
,	"sutkrilod": 5
,	"sutkrilop": 5
,	"sutcrtad": 0
,	"sutcrtap": 0
,	"sutizvanad": 0
,	"sutizvanap": 0
,	"sutkontrad": 0
,	"sutkontrap": 0
,	"sutprolazd": 0
,	"sutprolazp": 0
,	"asistencija": 0
,	"tehnickih": 0
,	"osvojenih": 0
,	"iskljucenja": 0
,	"zutih": 0
,	"crvenih": 0
,	"skrivljenihsedmeraca": 0
,	"izborenihsedmeraca": 0
,	"obraned": 0
,	"obranep": 0
,	"obranekrilod": 0
,	"obranekrilop": 0
,	"obraneizvanad": 0
,	"obraneizvanap": 0
,	"obranekontrad": 0
,	"obranekontrap": 0
,	"obraneprolazd": 0
,	"obraneprolazp": 0
,	"sutsedmeracd": 0
,	"sutsedmeracp": 0
,	"obranesedmeracd": 0
,	"obranesedmeracp": 0
,	"obranecrtap": 0
,	"obranecrtad": 0
,	"izborenihiskljucenja": 0
,	"blokova": 0
,	"asistencijacepelin": 0
,	"bodova": 0
,	sekundi: null
,	"valigrac": 5
,	"valgolman": 5
,	rezefekt: null
,	"sutizdalekad": 0
,	"sutizdalekap": 0
,	"obraneizdalekad": 0
,	"obraneizdalekap": 0
,	starter: null
,	"plavih": 0
,	"pasova": 0
,	nagrada: null
,	"ekipa": 166
,	"lokalid": 497
,	"lokalutakmica": 18
,	"rp_promjena": "207653496"
,	"rp_dodan": "207489834"
,	rp_ostaviti: null
,	"i": "Victoria Eva"
,	"p": "VranjeЕЎ"
,	"sl": ""
,	pz: null
}
, {
	"broj": 117184
,	"igrac": 124383
,	"ime": "AnД‘ela Kristina"
,	"prezime": "Selak"
,	"dres": 8
,	"rbekipa": 1
,	"utakmica": 6998
,	"uredjaj": 567
,	"tipigraca": 0
,	"sutd": 7
,	"sutp": 7
,	"sutkrilod": 6
,	"sutkrilop": 6
,	"sutcrtad": 0
,	"sutcrtap": 0
,	"sutizvanad": 0
,	"sutizvanap": 0
,	"sutkontrad": 0
,	"sutkontrap": 0
,	"sutprolazd": 0
,	"sutprolazp": 0
,	"asistencija": 0
,	"tehnickih": 0
,	"osvojenih": 0
,	"iskljucenja": 0
,	"zutih": 1
,	"crvenih": 0
,	"skrivljenihsedmeraca": 0
,	"izborenihsedmeraca": 0
,	"obraned": 0
,	"obranep": 0
,	"obranekrilod": 0
,	"obranekrilop": 0
,	"obraneizvanad": 0
,	"obraneizvanap": 0
,	"obranekontrad": 0
,	"obranekontrap": 0
,	"obraneprolazd": 0
,	"obraneprolazp": 0
,	"sutsedmeracd": 1
,	"sutsedmeracp": 1
,	"obranesedmeracd": 0
,	"obranesedmeracp": 0
,	"obranecrtap": 0
,	"obranecrtad": 0
,	"izborenihiskljucenja": 0
,	"blokova": 0
,	"asistencijacepelin": 0
,	"bodova": 0
,	sekundi: null
,	"valigrac": 6.5
,	"valgolman": 6.5
,	rezefekt: null
,	"sutizdalekad": 0
,	"sutizdalekap": 0
,	"obraneizdalekad": 0
,	"obraneizdalekap": 0
,	starter: null
,	"plavih": 0
,	"pasova": 0
,	nagrada: null
,	"ekipa": 166
,	"lokalid": 493
,	"lokalutakmica": 18
,	"rp_promjena": "207653168"
,	"rp_dodan": "207489826"
,	rp_ostaviti: null
,	"i": "AnД‘ela Kristina"
,	"p": "Selak"
,	"sl": ""
,	pz: null
}
, {
	"broj": 117206
,	"igrac": 125157
,	"ime": "Marta"
,	"prezime": "VidoviД‡"
,	"dres": 8
,	"rbekipa": 2
,	"utakmica": 6998
,	"uredjaj": 567
,	"tipigraca": 0
,	"sutd": 1
,	"sutp": 1
,	"sutkrilod": 1
,	"sutkrilop": 1
,	"sutcrtad": 0
,	"sutcrtap": 0
,	"sutizvanad": 0
,	"sutizvanap": 0
,	"sutkontrad": 0
,	"sutkontrap": 0
,	"sutprolazd": 0
,	"sutprolazp": 0
,	"asistencija": 0
,	"tehnickih": 0
,	"osvojenih": 0
,	"iskljucenja": 0
,	"zutih": 0
,	"crvenih": 0
,	"skrivljenihsedmeraca": 0
,	"izborenihsedmeraca": 0
,	"obraned": 0
,	"obranep": 0
,	"obranekrilod": 0
,	"obranekrilop": 0
,	"obraneizvanad": 0
,	"obraneizvanap": 0
,	"obranekontrad": 0
,	"obranekontrap": 0
,	"obraneprolazd": 0
,	"obraneprolazp": 0
,	"sutsedmeracd": 0
,	"sutsedmeracp": 0
,	"obranesedmeracd": 0
,	"obranesedmeracp": 0
,	"obranecrtap": 0
,	"obranecrtad": 0
,	"izborenihiskljucenja": 0
,	"blokova": 0
,	"asistencijacepelin": 0
,	"bodova": 0
,	sekundi: null
,	"valigrac": 1
,	"valgolman": 1
,	rezefekt: null
,	"sutizdalekad": 0
,	"sutizdalekap": 0
,	"obraneizdalekad": 0
,	"obraneizdalekap": 0
,	starter: null
,	"plavih": 0
,	"pasova": 0
,	nagrada: null
,	"ekipa": 165
,	"lokalid": 515
,	"lokalutakmica": 18
,	"rp_promjena": "207601042"
,	"rp_dodan": "207489882"
,	rp_ostaviti: null
,	"i": "Marta"
,	"p": "VidoviД‡"
,	"sl": ""
,	pz: null
}
, {
	"broj": 117195
,	"igrac": 121833
,	"ime": "Petra"
,	"prezime": "Gustin"
,	"dres": 9
,	"rbekipa": 2
,	"utakmica": 6998
,	"uredjaj": 567
,	"tipigraca": 0
,	"sutd": 1
,	"sutp": 1
,	"sutkrilod": 1
,	"sutkrilop": 1
,	"sutcrtad": 0
,	"sutcrtap": 0
,	"sutizvanad": 0
,	"sutizvanap": 0
,	"sutkontrad": 0
,	"sutkontrap": 0
,	"sutprolazd": 0
,	"sutprolazp": 0
,	"asistencija": 0
,	"tehnickih": 0
,	"osvojenih": 0
,	"iskljucenja": 0
,	"zutih": 0
,	"crvenih": 0
,	"skrivljenihsedmeraca": 0
,	"izborenihsedmeraca": 0
,	"obraned": 0
,	"obranep": 0
,	"obranekrilod": 0
,	"obranekrilop": 0
,	"obraneizvanad": 0
,	"obraneizvanap": 0
,	"obranekontrad": 0
,	"obranekontrap": 0
,	"obraneprolazd": 0
,	"obraneprolazp": 0
,	"sutsedmeracd": 0
,	"sutsedmeracp": 0
,	"obranesedmeracd": 0
,	"obranesedmeracp": 0
,	"obranecrtap": 0
,	"obranecrtad": 0
,	"izborenihiskljucenja": 0
,	"blokova": 0
,	"asistencijacepelin": 0
,	"bodova": 0
,	sekundi: null
,	"valigrac": 1
,	"valgolman": 1
,	rezefekt: null
,	"sutizdalekad": 0
,	"sutizdalekap": 0
,	"obraneizdalekad": 0
,	"obraneizdalekap": 0
,	starter: null
,	"plavih": 0
,	"pasova": 0
,	nagrada: null
,	"ekipa": 165
,	"lokalid": 504
,	"lokalutakmica": 18
,	"rp_promjena": "207642502"
,	"rp_dodan": "207489860"
,	rp_ostaviti: null
,	"i": "Petra"
,	"p": "Gustin"
,	"sl": ""
,	pz: null
}
, {
	"broj": 117190
,	"igrac": 127878
,	"ime": "Petra"
,	"prezime": "Jurilj"
,	"dres": 9
,	"rbekipa": 1
,	"utakmica": 6998
,	"uredjaj": 567
,	"tipigraca": 0
,	"sutd": 2
,	"sutp": 2
,	"sutkrilod": 2
,	"sutkrilop": 2
,	"sutcrtad": 0
,	"sutcrtap": 0
,	"sutizvanad": 0
,	"sutizvanap": 0
,	"sutkontrad": 0
,	"sutkontrap": 0
,	"sutprolazd": 0
,	"sutprolazp": 0
,	"asistencija": 0
,	"tehnickih": 0
,	"osvojenih": 0
,	"iskljucenja": 0
,	"zutih": 0
,	"crvenih": 0
,	"skrivljenihsedmeraca": 0
,	"izborenihsedmeraca": 0
,	"obraned": 0
,	"obranep": 0
,	"obranekrilod": 0
,	"obranekrilop": 0
,	"obraneizvanad": 0
,	"obraneizvanap": 0
,	"obranekontrad": 0
,	"obranekontrap": 0
,	"obraneprolazd": 0
,	"obraneprolazp": 0
,	"sutsedmeracd": 0
,	"sutsedmeracp": 0
,	"obranesedmeracd": 0
,	"obranesedmeracp": 0
,	"obranecrtap": 0
,	"obranecrtad": 0
,	"izborenihiskljucenja": 0
,	"blokova": 0
,	"asistencijacepelin": 0
,	"bodova": 0
,	sekundi: null
,	"valigrac": 2
,	"valgolman": 2
,	rezefekt: null
,	"sutizdalekad": 0
,	"sutizdalekap": 0
,	"obraneizdalekad": 0
,	"obraneizdalekap": 0
,	starter: null
,	"plavih": 0
,	"pasova": 0
,	nagrada: null
,	"ekipa": 166
,	"lokalid": 499
,	"lokalutakmica": 18
,	"rp_promjena": "207636076"
,	"rp_dodan": "207489838"
,	rp_ostaviti: null
,	"i": "Petra"
,	"p": "Jurilj"
,	"sl": ""
,	pz: null
}
, {
	"broj": 117191
,	"igrac": 120682
,	"ime": "Josipa"
,	"prezime": "BebiД‡"
,	"dres": 10
,	"rbekipa": 2
,	"utakmica": 6998
,	"uredjaj": 567
,	"tipigraca": 0
,	"sutd": 2
,	"sutp": 2
,	"sutkrilod": 2
,	"sutkrilop": 2
,	"sutcrtad": 0
,	"sutcrtap": 0
,	"sutizvanad": 0
,	"sutizvanap": 0
,	"sutkontrad": 0
,	"sutkontrap": 0
,	"sutprolazd": 0
,	"sutprolazp": 0
,	"asistencija": 0
,	"tehnickih": 0
,	"osvojenih": 0
,	"iskljucenja": 0
,	"zutih": 0
,	"crvenih": 0
,	"skrivljenihsedmeraca": 0
,	"izborenihsedmeraca": 0
,	"obraned": 0
,	"obranep": 0
,	"obranekrilod": 0
,	"obranekrilop": 0
,	"obraneizvanad": 0
,	"obraneizvanap": 0
,	"obranekontrad": 0
,	"obranekontrap": 0
,	"obraneprolazd": 0
,	"obraneprolazp": 0
,	"sutsedmeracd": 0
,	"sutsedmeracp": 0
,	"obranesedmeracd": 0
,	"obranesedmeracp": 0
,	"obranecrtap": 0
,	"obranecrtad": 0
,	"izborenihiskljucenja": 0
,	"blokova": 0
,	"asistencijacepelin": 0
,	"bodova": 0
,	sekundi: null
,	"valigrac": 2
,	"valgolman": 2
,	rezefekt: null
,	"sutizdalekad": 0
,	"sutizdalekap": 0
,	"obraneizdalekad": 0
,	"obraneizdalekap": 0
,	starter: null
,	"plavih": 0
,	"pasova": 0
,	nagrada: null
,	"ekipa": 165
,	"lokalid": 500
,	"lokalutakmica": 18
,	"rp_promjena": "207653204"
,	"rp_dodan": "207489852"
,	rp_ostaviti: null
,	"i": "Josipa"
,	"p": "BebiД‡"
,	"sl": ""
,	pz: null
}
, {
	"broj": 117179
,	"igrac": 122253
,	"ime": "Nina"
,	"prezime": "JuriДЌiД‡"
,	"dres": 10
,	"rbekipa": 1
,	"utakmica": 6998
,	"uredjaj": 567
,	"tipigraca": 0
,	"sutd": 4
,	"sutp": 4
,	"sutkrilod": 4
,	"sutkrilop": 4
,	"sutcrtad": 0
,	"sutcrtap": 0
,	"sutizvanad": 0
,	"sutizvanap": 0
,	"sutkontrad": 0
,	"sutkontrap": 0
,	"sutprolazd": 0
,	"sutprolazp": 0
,	"asistencija": 0
,	"tehnickih": 0
,	"osvojenih": 0
,	"iskljucenja": 0
,	"zutih": 1
,	"crvenih": 0
,	"skrivljenihsedmeraca": 0
,	"izborenihsedmeraca": 0
,	"obraned": 0
,	"obranep": 0
,	"obranekrilod": 0
,	"obranekrilop": 0
,	"obraneizvanad": 0
,	"obraneizvanap": 0
,	"obranekontrad": 0
,	"obranekontrap": 0
,	"obraneprolazd": 0
,	"obraneprolazp": 0
,	"sutsedmeracd": 0
,	"sutsedmeracp": 0
,	"obranesedmeracd": 0
,	"obranesedmeracp": 0
,	"obranecrtap": 0
,	"obranecrtad": 0
,	"izborenihiskljucenja": 0
,	"blokova": 0
,	"asistencijacepelin": 0
,	"bodova": 0
,	sekundi: null
,	"valigrac": 4
,	"valgolman": 4
,	rezefekt: null
,	"sutizdalekad": 0
,	"sutizdalekap": 0
,	"obraneizdalekad": 0
,	"obraneizdalekap": 0
,	starter: null
,	"plavih": 0
,	"pasova": 0
,	nagrada: null
,	"ekipa": 166
,	"lokalid": 488
,	"lokalutakmica": 18
,	"rp_promjena": "207653230"
,	"rp_dodan": "207489816"
,	rp_ostaviti: null
,	"i": "Nina"
,	"p": "JuriДЌiД‡"
,	"sl": ""
,	pz: null
}
, {
	"broj": 117202
,	"igrac": 124629
,	"ime": "AnД‘ela"
,	"prezime": "SuЕЎak"
,	"dres": 11
,	"rbekipa": 2
,	"utakmica": 6998
,	"uredjaj": 567
,	"tipigraca": 0
,	"sutd": 11
,	"sutp": 12
,	"sutkrilod": 8
,	"sutkrilop": 8
,	"sutcrtad": 0
,	"sutcrtap": 0
,	"sutizvanad": 0
,	"sutizvanap": 0
,	"sutkontrad": 0
,	"sutkontrap": 0
,	"sutprolazd": 0
,	"sutprolazp": 0
,	"asistencija": 0
,	"tehnickih": 0
,	"osvojenih": 0
,	"iskljucenja": 0
,	"zutih": 0
,	"crvenih": 0
,	"skrivljenihsedmeraca": 0
,	"izborenihsedmeraca": 0
,	"obraned": 0
,	"obranep": 0
,	"obranekrilod": 0
,	"obranekrilop": 0
,	"obraneizvanad": 0
,	"obraneizvanap": 0
,	"obranekontrad": 0
,	"obranekontrap": 0
,	"obraneprolazd": 0
,	"obraneprolazp": 0
,	"sutsedmeracd": 3
,	"sutsedmeracp": 4
,	"obranesedmeracd": 0
,	"obranesedmeracp": 0
,	"obranecrtap": 0
,	"obranecrtad": 0
,	"izborenihiskljucenja": 0
,	"blokova": 0
,	"asistencijacepelin": 0
,	"bodova": 0
,	sekundi: null
,	"valigrac": 8.5
,	"valgolman": 8.5
,	rezefekt: null
,	"sutizdalekad": 0
,	"sutizdalekap": 0
,	"obraneizdalekad": 0
,	"obraneizdalekap": 0
,	starter: null
,	"plavih": 0
,	"pasova": 0
,	nagrada: null
,	"ekipa": 165
,	"lokalid": 511
,	"lokalutakmica": 18
,	"rp_promjena": "207662748"
,	"rp_dodan": "207489874"
,	rp_ostaviti: null
,	"i": "AnД‘ela"
,	"p": "SuЕЎak"
,	"sl": ""
,	pz: null
}
, {
	"broj": 117193
,	"igrac": 121483
,	"ime": "Laura"
,	"prezime": "Erceg"
,	"dres": 12
,	"rbekipa": 2
,	"utakmica": 6998
,	"uredjaj": 567
,	"tipigraca": 0
,	"sutd": 0
,	"sutp": 0
,	"sutkrilod": 0
,	"sutkrilop": 0
,	"sutcrtad": 0
,	"sutcrtap": 0
,	"sutizvanad": 0
,	"sutizvanap": 0
,	"sutkontrad": 0
,	"sutkontrap": 0
,	"sutprolazd": 0
,	"sutprolazp": 0
,	"asistencija": 0
,	"tehnickih": 0
,	"osvojenih": 0
,	"iskljucenja": 0
,	"zutih": 0
,	"crvenih": 0
,	"skrivljenihsedmeraca": 0
,	"izborenihsedmeraca": 0
,	"obraned": 0
,	"obranep": 0
,	"obranekrilod": 0
,	"obranekrilop": 0
,	"obraneizvanad": 0
,	"obraneizvanap": 0
,	"obranekontrad": 0
,	"obranekontrap": 0
,	"obraneprolazd": 0
,	"obraneprolazp": 0
,	"sutsedmeracd": 0
,	"sutsedmeracp": 0
,	"obranesedmeracd": 0
,	"obranesedmeracp": 0
,	"obranecrtap": 0
,	"obranecrtad": 0
,	"izborenihiskljucenja": 0
,	"blokova": 0
,	"asistencijacepelin": 0
,	"bodova": 0
,	sekundi: null
,	"valigrac": 0
,	"valgolman": 0
,	rezefekt: null
,	"sutizdalekad": 0
,	"sutizdalekap": 0
,	"obraneizdalekad": 0
,	"obraneizdalekap": 0
,	starter: null
,	"plavih": 0
,	"pasova": 0
,	nagrada: null
,	"ekipa": 165
,	"lokalid": 502
,	"lokalutakmica": 18
,	"rp_promjena": "207591030"
,	"rp_dodan": "207489856"
,	rp_ostaviti: null
,	"i": "Laura"
,	"p": "Erceg"
,	"sl": ""
,	pz: null
}
, {
	"broj": 117185
,	"igrac": 127900
,	"ime": "Ana"
,	"prezime": "StipiДЌeviД‡"
,	"dres": 12
,	"rbekipa": 1
,	"utakmica": 6998
,	"uredjaj": 567
,	"tipigraca": 0
,	"sutd": 0
,	"sutp": 0
,	"sutkrilod": 0
,	"sutkrilop": 0
,	"sutcrtad": 0
,	"sutcrtap": 0
,	"sutizvanad": 0
,	"sutizvanap": 0
,	"sutkontrad": 0
,	"sutkontrap": 0
,	"sutprolazd": 0
,	"sutprolazp": 0
,	"asistencija": 0
,	"tehnickih": 0
,	"osvojenih": 0
,	"iskljucenja": 0
,	"zutih": 0
,	"crvenih": 0
,	"skrivljenihsedmeraca": 0
,	"izborenihsedmeraca": 0
,	"obraned": 0
,	"obranep": 0
,	"obranekrilod": 0
,	"obranekrilop": 0
,	"obraneizvanad": 0
,	"obraneizvanap": 0
,	"obranekontrad": 0
,	"obranekontrap": 0
,	"obraneprolazd": 0
,	"obraneprolazp": 0
,	"sutsedmeracd": 0
,	"sutsedmeracp": 0
,	"obranesedmeracd": 0
,	"obranesedmeracp": 0
,	"obranecrtap": 0
,	"obranecrtad": 0
,	"izborenihiskljucenja": 0
,	"blokova": 0
,	"asistencijacepelin": 0
,	"bodova": 0
,	sekundi: null
,	"valigrac": 0
,	"valgolman": 0
,	rezefekt: null
,	"sutizdalekad": 0
,	"sutizdalekap": 0
,	"obraneizdalekad": 0
,	"obraneizdalekap": 0
,	starter: null
,	"plavih": 0
,	"pasova": 0
,	nagrada: null
,	"ekipa": 166
,	"lokalid": 494
,	"lokalutakmica": 18
,	"rp_promjena": "207591058"
,	"rp_dodan": "207489828"
,	rp_ostaviti: null
,	"i": "Ana"
,	"p": "StipiДЌeviД‡"
,	"sl": ""
,	pz: null
}
, {
	"broj": 117192
,	"igrac": 126504
,	"ime": "Lucija"
,	"prezime": "DruЕѕijaniД‡"
,	"dres": 14
,	"rbekipa": 2
,	"utakmica": 6998
,	"uredjaj": 567
,	"tipigraca": 0
,	"sutd": 1
,	"sutp": 1
,	"sutkrilod": 1
,	"sutkrilop": 1
,	"sutcrtad": 0
,	"sutcrtap": 0
,	"sutizvanad": 0
,	"sutizvanap": 0
,	"sutkontrad": 0
,	"sutkontrap": 0
,	"sutprolazd": 0
,	"sutprolazp": 0
,	"asistencija": 0
,	"tehnickih": 0
,	"osvojenih": 0
,	"iskljucenja": 0
,	"zutih": 0
,	"crvenih": 0
,	"skrivljenihsedmeraca": 0
,	"izborenihsedmeraca": 0
,	"obraned": 0
,	"obranep": 0
,	"obranekrilod": 0
,	"obranekrilop": 0
,	"obraneizvanad": 0
,	"obraneizvanap": 0
,	"obranekontrad": 0
,	"obranekontrap": 0
,	"obraneprolazd": 0
,	"obraneprolazp": 0
,	"sutsedmeracd": 0
,	"sutsedmeracp": 0
,	"obranesedmeracd": 0
,	"obranesedmeracp": 0
,	"obranecrtap": 0
,	"obranecrtad": 0
,	"izborenihiskljucenja": 0
,	"blokova": 0
,	"asistencijacepelin": 0
,	"bodova": 0
,	sekundi: null
,	"valigrac": 1
,	"valgolman": 1
,	rezefekt: null
,	"sutizdalekad": 0
,	"sutizdalekap": 0
,	"obraneizdalekad": 0
,	"obraneizdalekap": 0
,	starter: null
,	"plavih": 0
,	"pasova": 0
,	nagrada: null
,	"ekipa": 165
,	"lokalid": 501
,	"lokalutakmica": 18
,	"rp_promjena": "207591240"
,	"rp_dodan": "207489854"
,	rp_ostaviti: null
,	"i": "Lucija"
,	"p": "DruЕѕijaniД‡"
,	"sl": ""
,	pz: null
}
, {
	"broj": 117181
,	"igrac": 137465
,	"ime": "Tone"
,	"prezime": "Kajtazi"
,	"dres": 14
,	"rbekipa": 1
,	"utakmica": 6998
,	"uredjaj": 567
,	"tipigraca": 0
,	"sutd": 0
,	"sutp": 0
,	"sutkrilod": 0
,	"sutkrilop": 0
,	"sutcrtad": 0
,	"sutcrtap": 0
,	"sutizvanad": 0
,	"sutizvanap": 0
,	"sutkontrad": 0
,	"sutkontrap": 0
,	"sutprolazd": 0
,	"sutprolazp": 0
,	"asistencija": 0
,	"tehnickih": 0
,	"osvojenih": 0
,	"iskljucenja": 0
,	"zutih": 0
,	"crvenih": 0
,	"skrivljenihsedmeraca": 0
,	"izborenihsedmeraca": 0
,	"obraned": 0
,	"obranep": 0
,	"obranekrilod": 0
,	"obranekrilop": 0
,	"obraneizvanad": 0
,	"obraneizvanap": 0
,	"obranekontrad": 0
,	"obranekontrap": 0
,	"obraneprolazd": 0
,	"obraneprolazp": 0
,	"sutsedmeracd": 0
,	"sutsedmeracp": 0
,	"obranesedmeracd": 0
,	"obranesedmeracp": 0
,	"obranecrtap": 0
,	"obranecrtad": 0
,	"izborenihiskljucenja": 0
,	"blokova": 0
,	"asistencijacepelin": 0
,	"bodova": 0
,	sekundi: null
,	"valigrac": 0
,	"valgolman": 0
,	rezefekt: null
,	"sutizdalekad": 0
,	"sutizdalekap": 0
,	"obraneizdalekad": 0
,	"obraneizdalekap": 0
,	starter: null
,	"plavih": 0
,	"pasova": 0
,	nagrada: null
,	"ekipa": 166
,	"lokalid": 490
,	"lokalutakmica": 18
,	"rp_promjena": "207591042"
,	"rp_dodan": "207489820"
,	rp_ostaviti: null
,	"i": "Tone"
,	"p": "Kajtazi"
,	"sl": ""
,	pz: null
}
, {
	"broj": 117187
,	"igrac": 127902
,	"ime": "Lara"
,	"prezime": "Е evelj"
,	"dres": 15
,	"rbekipa": 1
,	"utakmica": 6998
,	"uredjaj": 567
,	"tipigraca": 0
,	"sutd": 0
,	"sutp": 0
,	"sutkrilod": 0
,	"sutkrilop": 0
,	"sutcrtad": 0
,	"sutcrtap": 0
,	"sutizvanad": 0
,	"sutizvanap": 0
,	"sutkontrad": 0
,	"sutkontrap": 0
,	"sutprolazd": 0
,	"sutprolazp": 0
,	"asistencija": 0
,	"tehnickih": 0
,	"osvojenih": 0
,	"iskljucenja": 0
,	"zutih": 0
,	"crvenih": 0
,	"skrivljenihsedmeraca": 0
,	"izborenihsedmeraca": 0
,	"obraned": 0
,	"obranep": 0
,	"obranekrilod": 0
,	"obranekrilop": 0
,	"obraneizvanad": 0
,	"obraneizvanap": 0
,	"obranekontrad": 0
,	"obranekontrap": 0
,	"obraneprolazd": 0
,	"obraneprolazp": 0
,	"sutsedmeracd": 0
,	"sutsedmeracp": 0
,	"obranesedmeracd": 0
,	"obranesedmeracp": 0
,	"obranecrtap": 0
,	"obranecrtad": 0
,	"izborenihiskljucenja": 0
,	"blokova": 0
,	"asistencijacepelin": 0
,	"bodova": 0
,	sekundi: null
,	"valigrac": 0
,	"valgolman": 0
,	rezefekt: null
,	"sutizdalekad": 0
,	"sutizdalekap": 0
,	"obraneizdalekad": 0
,	"obraneizdalekap": 0
,	starter: null
,	"plavih": 0
,	"pasova": 0
,	nagrada: null
,	"ekipa": 166
,	"lokalid": 496
,	"lokalutakmica": 18
,	"rp_promjena": "207591064"
,	"rp_dodan": "207489832"
,	rp_ostaviti: null
,	"i": "Lara"
,	"p": "Е evelj"
,	"sl": ""
,	pz: null
}
, {
	"broj": 117183
,	"igrac": 128871
,	"ime": "Lucija"
,	"prezime": "RavliД‡"
,	"dres": 16
,	"rbekipa": 1
,	"utakmica": 6998
,	"uredjaj": 567
,	"tipigraca": 0
,	"sutd": 0
,	"sutp": 0
,	"sutkrilod": 0
,	"sutkrilop": 0
,	"sutcrtad": 0
,	"sutcrtap": 0
,	"sutizvanad": 0
,	"sutizvanap": 0
,	"sutkontrad": 0
,	"sutkontrap": 0
,	"sutprolazd": 0
,	"sutprolazp": 0
,	"asistencija": 0
,	"tehnickih": 0
,	"osvojenih": 0
,	"iskljucenja": 0
,	"zutih": 0
,	"crvenih": 0
,	"skrivljenihsedmeraca": 0
,	"izborenihsedmeraca": 0
,	"obraned": 0
,	"obranep": 0
,	"obranekrilod": 0
,	"obranekrilop": 0
,	"obraneizvanad": 0
,	"obraneizvanap": 0
,	"obranekontrad": 0
,	"obranekontrap": 0
,	"obraneprolazd": 0
,	"obraneprolazp": 0
,	"sutsedmeracd": 0
,	"sutsedmeracp": 0
,	"obranesedmeracd": 0
,	"obranesedmeracp": 0
,	"obranecrtap": 0
,	"obranecrtad": 0
,	"izborenihiskljucenja": 0
,	"blokova": 0
,	"asistencijacepelin": 0
,	"bodova": 0
,	sekundi: null
,	"valigrac": 0
,	"valgolman": 0
,	rezefekt: null
,	"sutizdalekad": 0
,	"sutizdalekap": 0
,	"obraneizdalekad": 0
,	"obraneizdalekap": 0
,	starter: null
,	"plavih": 0
,	"pasova": 0
,	nagrada: null
,	"ekipa": 166
,	"lokalid": 492
,	"lokalutakmica": 18
,	"rp_promjena": "207591052"
,	"rp_dodan": "207489824"
,	rp_ostaviti: null
,	"i": "Lucija"
,	"p": "RavliД‡"
,	"sl": ""
,	pz: null
}
, {
	"broj": 117205
,	"igrac": 135039
,	"ime": "Jelena"
,	"prezime": "VidoviД‡"
,	"dres": 16
,	"rbekipa": 2
,	"utakmica": 6998
,	"uredjaj": 567
,	"tipigraca": 0
,	"sutd": 0
,	"sutp": 0
,	"sutkrilod": 0
,	"sutkrilop": 0
,	"sutcrtad": 0
,	"sutcrtap": 0
,	"sutizvanad": 0
,	"sutizvanap": 0
,	"sutkontrad": 0
,	"sutkontrap": 0
,	"sutprolazd": 0
,	"sutprolazp": 0
,	"asistencija": 0
,	"tehnickih": 0
,	"osvojenih": 0
,	"iskljucenja": 0
,	"zutih": 0
,	"crvenih": 0
,	"skrivljenihsedmeraca": 0
,	"izborenihsedmeraca": 0
,	"obraned": 0
,	"obranep": 0
,	"obranekrilod": 0
,	"obranekrilop": 0
,	"obraneizvanad": 0
,	"obraneizvanap": 0
,	"obranekontrad": 0
,	"obranekontrap": 0
,	"obraneprolazd": 0
,	"obraneprolazp": 0
,	"sutsedmeracd": 0
,	"sutsedmeracp": 0
,	"obranesedmeracd": 0
,	"obranesedmeracp": 0
,	"obranecrtap": 0
,	"obranecrtad": 0
,	"izborenihiskljucenja": 0
,	"blokova": 0
,	"asistencijacepelin": 0
,	"bodova": 0
,	sekundi: null
,	"valigrac": 0
,	"valgolman": 0
,	rezefekt: null
,	"sutizdalekad": 0
,	"sutizdalekap": 0
,	"obraneizdalekad": 0
,	"obraneizdalekap": 0
,	starter: null
,	"plavih": 0
,	"pasova": 0
,	nagrada: null
,	"ekipa": 165
,	"lokalid": 514
,	"lokalutakmica": 18
,	"rp_promjena": "207591070"
,	"rp_dodan": "207489880"
,	rp_ostaviti: null
,	"i": "Jelena"
,	"p": "VidoviД‡"
,	"sl": ""
,	pz: null
}
, {
	"broj": 117203
,	"igrac": 128488
,	"ime": "Rita"
,	"prezime": "Е iljeg"
,	"dres": 17
,	"rbekipa": 2
,	"utakmica": 6998
,	"uredjaj": 567
,	"tipigraca": 0
,	"sutd": 3
,	"sutp": 3
,	"sutkrilod": 3
,	"sutkrilop": 3
,	"sutcrtad": 0
,	"sutcrtap": 0
,	"sutizvanad": 0
,	"sutizvanap": 0
,	"sutkontrad": 0
,	"sutkontrap": 0
,	"sutprolazd": 0
,	"sutprolazp": 0
,	"asistencija": 0
,	"tehnickih": 0
,	"osvojenih": 0
,	"iskljucenja": 0
,	"zutih": 0
,	"crvenih": 0
,	"skrivljenihsedmeraca": 0
,	"izborenihsedmeraca": 0
,	"obraned": 0
,	"obranep": 0
,	"obranekrilod": 0
,	"obranekrilop": 0
,	"obraneizvanad": 0
,	"obraneizvanap": 0
,	"obranekontrad": 0
,	"obranekontrap": 0
,	"obraneprolazd": 0
,	"obraneprolazp": 0
,	"sutsedmeracd": 0
,	"sutsedmeracp": 0
,	"obranesedmeracd": 0
,	"obranesedmeracp": 0
,	"obranecrtap": 0
,	"obranecrtad": 0
,	"izborenihiskljucenja": 0
,	"blokova": 0
,	"asistencijacepelin": 0
,	"bodova": 0
,	sekundi: null
,	"valigrac": 3
,	"valgolman": 3
,	rezefekt: null
,	"sutizdalekad": 0
,	"sutizdalekap": 0
,	"obraneizdalekad": 0
,	"obraneizdalekap": 0
,	starter: null
,	"plavih": 0
,	"pasova": 0
,	nagrada: null
,	"ekipa": 165
,	"lokalid": 512
,	"lokalutakmica": 18
,	"rp_promjena": "207610910"
,	"rp_dodan": "207489876"
,	rp_ostaviti: null
,	"i": "Rita"
,	"p": "Е iljeg"
,	"sl": ""
,	pz: null
}
, {
	"broj": 117178
,	"igrac": 134558
,	"ime": "Ana"
,	"prezime": "Е alinoviД‡"
,	"dres": 17
,	"rbekipa": 1
,	"utakmica": 6998
,	"uredjaj": 567
,	"tipigraca": 0
,	"sutd": 0
,	"sutp": 0
,	"sutkrilod": 0
,	"sutkrilop": 0
,	"sutcrtad": 0
,	"sutcrtap": 0
,	"sutizvanad": 0
,	"sutizvanap": 0
,	"sutkontrad": 0
,	"sutkontrap": 0
,	"sutprolazd": 0
,	"sutprolazp": 0
,	"asistencija": 0
,	"tehnickih": 0
,	"osvojenih": 0
,	"iskljucenja": 0
,	"zutih": 0
,	"crvenih": 0
,	"skrivljenihsedmeraca": 0
,	"izborenihsedmeraca": 0
,	"obraned": 0
,	"obranep": 0
,	"obranekrilod": 0
,	"obranekrilop": 0
,	"obraneizvanad": 0
,	"obraneizvanap": 0
,	"obranekontrad": 0
,	"obranekontrap": 0
,	"obraneprolazd": 0
,	"obraneprolazp": 0
,	"sutsedmeracd": 0
,	"sutsedmeracp": 0
,	"obranesedmeracd": 0
,	"obranesedmeracp": 0
,	"obranecrtap": 0
,	"obranecrtad": 0
,	"izborenihiskljucenja": 0
,	"blokova": 0
,	"asistencijacepelin": 0
,	"bodova": 0
,	sekundi: null
,	"valigrac": 0
,	"valgolman": 0
,	rezefekt: null
,	"sutizdalekad": 0
,	"sutizdalekap": 0
,	"obraneizdalekad": 0
,	"obraneizdalekap": 0
,	starter: null
,	"plavih": 0
,	"pasova": 0
,	nagrada: null
,	"ekipa": 166
,	"lokalid": 487
,	"lokalutakmica": 18
,	"rp_promjena": "207591062"
,	"rp_dodan": "207489814"
,	rp_ostaviti: null
,	"i": "Ana"
,	"p": "Е alinoviД‡"
,	"sl": ""
,	pz: null
}
, {
	"broj": 117196
,	"igrac": 122028
,	"ime": "Martina"
,	"prezime": "IliД‡"
,	"dres": 18
,	"rbekipa": 2
,	"utakmica": 6998
,	"uredjaj": 567
,	"tipigraca": 0
,	"sutd": 1
,	"sutp": 1
,	"sutkrilod": 1
,	"sutkrilop": 1
,	"sutcrtad": 0
,	"sutcrtap": 0
,	"sutizvanad": 0
,	"sutizvanap": 0
,	"sutkontrad": 0
,	"sutkontrap": 0
,	"sutprolazd": 0
,	"sutprolazp": 0
,	"asistencija": 0
,	"tehnickih": 0
,	"osvojenih": 0
,	"iskljucenja": 0
,	"zutih": 0
,	"crvenih": 0
,	"skrivljenihsedmeraca": 0
,	"izborenihsedmeraca": 0
,	"obraned": 0
,	"obranep": 0
,	"obranekrilod": 0
,	"obranekrilop": 0
,	"obraneizvanad": 0
,	"obraneizvanap": 0
,	"obranekontrad": 0
,	"obranekontrap": 0
,	"obraneprolazd": 0
,	"obraneprolazp": 0
,	"sutsedmeracd": 0
,	"sutsedmeracp": 0
,	"obranesedmeracd": 0
,	"obranesedmeracp": 0
,	"obranecrtap": 0
,	"obranecrtad": 0
,	"izborenihiskljucenja": 0
,	"blokova": 0
,	"asistencijacepelin": 0
,	"bodova": 0
,	sekundi: null
,	"valigrac": 1
,	"valgolman": 1
,	rezefekt: null
,	"sutizdalekad": 0
,	"sutizdalekap": 0
,	"obraneizdalekad": 0
,	"obraneizdalekap": 0
,	starter: null
,	"plavih": 0
,	"pasova": 0
,	nagrada: null
,	"ekipa": 165
,	"lokalid": 505
,	"lokalutakmica": 18
,	"rp_promjena": "207642448"
,	"rp_dodan": "207489862"
,	rp_ostaviti: null
,	"i": "Martina"
,	"p": "IliД‡"
,	"sl": ""
,	pz: null
}
, {
	"broj": 117204
,	"igrac": 128489
,	"ime": "Sara"
,	"prezime": "VatoviД‡"
,	"dres": 19
,	"rbekipa": 2
,	"utakmica": 6998
,	"uredjaj": 567
,	"tipigraca": 0
,	"sutd": 0
,	"sutp": 0
,	"sutkrilod": 0
,	"sutkrilop": 0
,	"sutcrtad": 0
,	"sutcrtap": 0
,	"sutizvanad": 0
,	"sutizvanap": 0
,	"sutkontrad": 0
,	"sutkontrap": 0
,	"sutprolazd": 0
,	"sutprolazp": 0
,	"asistencija": 0
,	"tehnickih": 0
,	"osvojenih": 0
,	"iskljucenja": 0
,	"zutih": 0
,	"crvenih": 0
,	"skrivljenihsedmeraca": 0
,	"izborenihsedmeraca": 0
,	"obraned": 0
,	"obranep": 0
,	"obranekrilod": 0
,	"obranekrilop": 0
,	"obraneizvanad": 0
,	"obraneizvanap": 0
,	"obranekontrad": 0
,	"obranekontrap": 0
,	"obraneprolazd": 0
,	"obraneprolazp": 0
,	"sutsedmeracd": 0
,	"sutsedmeracp": 0
,	"obranesedmeracd": 0
,	"obranesedmeracp": 0
,	"obranecrtap": 0
,	"obranecrtad": 0
,	"izborenihiskljucenja": 0
,	"blokova": 0
,	"asistencijacepelin": 0
,	"bodova": 0
,	sekundi: null
,	"valigrac": 0
,	"valgolman": 0
,	rezefekt: null
,	"sutizdalekad": 0
,	"sutizdalekap": 0
,	"obraneizdalekad": 0
,	"obraneizdalekap": 0
,	starter: null
,	"plavih": 0
,	"pasova": 0
,	nagrada: null
,	"ekipa": 165
,	"lokalid": 513
,	"lokalutakmica": 18
,	"rp_promjena": "207591068"
,	"rp_dodan": "207489878"
,	rp_ostaviti: null
,	"i": "Sara"
,	"p": "VatoviД‡"
,	"sl": ""
,	pz: null
}
, {
	"broj": 117198
,	"igrac": 123351
,	"ime": "Katarina"
,	"prezime": "MikuliД‡"
,	"dres": 20
,	"rbekipa": 2
,	"utakmica": 6998
,	"uredjaj": 567
,	"tipigraca": 0
,	"sutd": 0
,	"sutp": 0
,	"sutkrilod": 0
,	"sutkrilop": 0
,	"sutcrtad": 0
,	"sutcrtap": 0
,	"sutizvanad": 0
,	"sutizvanap": 0
,	"sutkontrad": 0
,	"sutkontrap": 0
,	"sutprolazd": 0
,	"sutprolazp": 0
,	"asistencija": 0
,	"tehnickih": 0
,	"osvojenih": 0
,	"iskljucenja": 0
,	"zutih": 0
,	"crvenih": 0
,	"skrivljenihsedmeraca": 0
,	"izborenihsedmeraca": 0
,	"obraned": 0
,	"obranep": 0
,	"obranekrilod": 0
,	"obranekrilop": 0
,	"obraneizvanad": 0
,	"obraneizvanap": 0
,	"obranekontrad": 0
,	"obranekontrap": 0
,	"obraneprolazd": 0
,	"obraneprolazp": 0
,	"sutsedmeracd": 0
,	"sutsedmeracp": 0
,	"obranesedmeracd": 0
,	"obranesedmeracp": 0
,	"obranecrtap": 0
,	"obranecrtad": 0
,	"izborenihiskljucenja": 0
,	"blokova": 0
,	"asistencijacepelin": 0
,	"bodova": 0
,	sekundi: null
,	"valigrac": 0
,	"valgolman": 0
,	rezefekt: null
,	"sutizdalekad": 0
,	"sutizdalekap": 0
,	"obraneizdalekad": 0
,	"obraneizdalekap": 0
,	starter: null
,	"plavih": 0
,	"pasova": 0
,	nagrada: null
,	"ekipa": 165
,	"lokalid": 507
,	"lokalutakmica": 18
,	"rp_promjena": "207591046"
,	"rp_dodan": "207489866"
,	rp_ostaviti: null
,	"i": "Katarina"
,	"p": "MikuliД‡"
,	"sl": ""
,	pz: null
}
]
, dogadjaji: [
{
	"broj": 278123
,	"e": 1
,	"sk": 3596
,	"vr": "59:56"
,	"pr": 1
,	"ekp": 1
,	"td": 10
,	"r1": 27
,	"r2": 27
,	ps: null
,	ss: null
,	ish: null
,	pz: null
,	gs: null
,	ob: null
,	"prg": 0
,	ig: null
,	"i": ""
,	"p": ""
}
, {
	"broj": 278112
,	"e": 2
,	"sk": 3596
,	"vr": "59:56"
,	"pr": 1
,	"ekp": 0
,	"td": 0
,	"r1": 27
,	"r2": 27
,	"ps": 3
,	"ss": 0
,	"ish": 0
,	"pz": 0
,	gs: null
,	ob: null
,	"prg": 0
,	"ig": 124629
,	"i": "AnД‘ela"
,	"p": "SuЕЎak"
}
, {
	"broj": 278122
,	"e": 2
,	"sk": 3580
,	"vr": "59:40"
,	"pr": 1
,	"ekp": 1
,	"td": 10
,	"r1": 27
,	"r2": 26
,	ps: null
,	ss: null
,	ish: null
,	pz: null
,	gs: null
,	ob: null
,	"prg": 0
,	ig: null
,	"i": ""
,	"p": ""
}
, {
	"broj": 278094
,	"e": 1
,	"sk": 3423
,	"vr": "57:03"
,	"pr": 1
,	"ekp": 0
,	"td": 0
,	"r1": 27
,	"r2": 26
,	"ps": 0
,	"ss": 0
,	"ish": 0
,	"pz": 0
,	gs: null
,	ob: null
,	"prg": 0
,	"ig": 125239
,	"i": "Victoria Eva"
,	"p": "VranjeЕЎ"
}
, {
	"broj": 278093
,	"e": 2
,	"sk": 3405
,	"vr": "56:45"
,	"pr": 1
,	"ekp": 0
,	"td": 0
,	"r1": 26
,	"r2": 26
,	"ps": 3
,	"ss": 0
,	"ish": 0
,	"pz": 0
,	gs: null
,	ob: null
,	"prg": 0
,	"ig": 124629
,	"i": "AnД‘ela"
,	"p": "SuЕЎak"
}
, {
	"broj": 278086
,	"e": 1
,	"sk": 3215
,	"vr": "53:35"
,	"pr": 1
,	"ekp": 0
,	"td": 0
,	"r1": 26
,	"r2": 25
,	"ps": 0
,	"ss": 0
,	"ish": 0
,	"pz": 0
,	gs: null
,	ob: null
,	"prg": 0
,	"ig": 122253
,	"i": "Nina"
,	"p": "JuriДЌiД‡"
}
, {
	"broj": 278084
,	"e": 2
,	"sk": 3204
,	"vr": "53:24"
,	"pr": 1
,	"ekp": 0
,	"td": 0
,	"r1": 25
,	"r2": 25
,	"ps": 0
,	"ss": 0
,	"ish": 0
,	"pz": 0
,	gs: null
,	ob: null
,	"prg": 0
,	"ig": 120682
,	"i": "Josipa"
,	"p": "BebiД‡"
}
, {
	"broj": 278082
,	"e": 1
,	"sk": 3182
,	"vr": "53:02"
,	"pr": 1
,	"ekp": 0
,	"td": 0
,	"r1": 25
,	"r2": 24
,	"ps": 3
,	"ss": 0
,	"ish": 0
,	"pz": 0
,	gs: null
,	ob: null
,	"prg": 0
,	"ig": 124383
,	"i": "AnД‘ela Kristina"
,	"p": "Selak"
}
, {
	"broj": 278074
,	"e": 2
,	"sk": 3111
,	"vr": "51:51"
,	"pr": 1
,	"ekp": 0
,	"td": 0
,	"r1": 24
,	"r2": 24
,	"ps": 0
,	"ss": 0
,	"ish": 0
,	"pz": 0
,	gs: null
,	ob: null
,	"prg": 0
,	"ig": 120682
,	"i": "Josipa"
,	"p": "BebiД‡"
}
, {
	"broj": 278073
,	"e": 1
,	"sk": 3087
,	"vr": "51:27"
,	"pr": 1
,	"ekp": 0
,	"td": 0
,	"r1": 24
,	"r2": 23
,	"ps": 0
,	"ss": 0
,	"ish": 0
,	"pz": 0
,	gs: null
,	ob: null
,	"prg": 0
,	"ig": 127856
,	"i": "Mia"
,	"p": "Bandur"
}
, {
	"broj": 278053
,	"e": 2
,	"sk": 2996
,	"vr": "49:56"
,	"pr": 1
,	"ekp": 0
,	"td": 0
,	"r1": 23
,	"r2": 23
,	"ps": 0
,	"ss": 0
,	"ish": 0
,	"pz": 0
,	gs: null
,	ob: null
,	"prg": 0
,	"ig": 123634
,	"i": "Petra"
,	"p": "ObЕЎivaДЌ"
}
, {
	"broj": 278050
,	"e": 2
,	"sk": 2963
,	"vr": "49:23"
,	"pr": 1
,	"ekp": 0
,	"td": 0
,	"r1": 23
,	"r2": 22
,	"ps": 3
,	"ss": 0
,	"ish": 0
,	"pz": 0
,	gs: null
,	ob: null
,	"prg": 0
,	"ig": 124629
,	"i": "AnД‘ela"
,	"p": "SuЕЎak"
}
, {
	"broj": 278044
,	"e": 1
,	"sk": 2906
,	"vr": "48:26"
,	"pr": 1
,	"ekp": 0
,	"td": 0
,	"r1": 23
,	"r2": 21
,	"ps": 0
,	"ss": 0
,	"ish": 0
,	"pz": 0
,	gs: null
,	ob: null
,	"prg": 0
,	"ig": 127856
,	"i": "Mia"
,	"p": "Bandur"
}
, {
	"broj": 278040
,	"e": 1
,	"sk": 2860
,	"vr": "47:40"
,	"pr": 1
,	"ekp": 0
,	"td": 0
,	"r1": 22
,	"r2": 21
,	"ps": 0
,	"ss": 0
,	"ish": 0
,	"pz": 0
,	gs: null
,	ob: null
,	"prg": 0
,	"ig": 127856
,	"i": "Mia"
,	"p": "Bandur"
}
, {
	"broj": 278039
,	"e": 2
,	"sk": 2846
,	"vr": "47:26"
,	"pr": 1
,	"ekp": 0
,	"td": 0
,	"r1": 21
,	"r2": 21
,	"ps": 0
,	"ss": 0
,	"ish": 0
,	"pz": 0
,	gs: null
,	ob: null
,	"prg": 0
,	"ig": 123634
,	"i": "Petra"
,	"p": "ObЕЎivaДЌ"
}
, {
	"broj": 278037
,	"e": 1
,	"sk": 2830
,	"vr": "47:10"
,	"pr": 1
,	"ekp": 0
,	"td": 0
,	"r1": 21
,	"r2": 20
,	"ps": 0
,	"ss": 0
,	"ish": 0
,	"pz": 0
,	gs: null
,	ob: null
,	"prg": 0
,	"ig": 134559
,	"i": "Danijela"
,	"p": "VujДЌiД‡"
}
, {
	"broj": 278023
,	"e": 2
,	"sk": 2727
,	"vr": "45:27"
,	"pr": 1
,	"ekp": 0
,	"td": 0
,	"r1": 20
,	"r2": 20
,	"ps": 0
,	"ss": 0
,	"ish": 0
,	"pz": 0
,	gs: null
,	ob: null
,	"prg": 0
,	"ig": 123634
,	"i": "Petra"
,	"p": "ObЕЎivaДЌ"
}
, {
	"broj": 278013
,	"e": 1
,	"sk": 2654
,	"vr": "44:14"
,	"pr": 1
,	"ekp": 0
,	"td": 0
,	"r1": 20
,	"r2": 19
,	"ps": 0
,	"ss": 0
,	"ish": 0
,	"pz": 0
,	gs: null
,	ob: null
,	"prg": 0
,	"ig": 124383
,	"i": "AnД‘ela Kristina"
,	"p": "Selak"
}
, {
	"broj": 278006
,	"e": 1
,	"sk": 2592
,	"vr": "43:12"
,	"pr": 1
,	"ekp": 0
,	"td": 0
,	"r1": 19
,	"r2": 19
,	"ps": 0
,	"ss": 0
,	"ish": 0
,	"pz": 0
,	gs: null
,	ob: null
,	"prg": 0
,	"ig": 124383
,	"i": "AnД‘ela Kristina"
,	"p": "Selak"
}
, {
	"broj": 277999
,	"e": 1
,	"sk": 2507
,	"vr": "41:47"
,	"pr": 1
,	"ekp": 0
,	"td": 0
,	"r1": 18
,	"r2": 19
,	"ps": 0
,	"ss": 0
,	"ish": 0
,	"pz": 0
,	gs: null
,	ob: null
,	"prg": 0
,	"ig": 124383
,	"i": "AnД‘ela Kristina"
,	"p": "Selak"
}
, {
	"broj": 277998
,	"e": 1
,	"sk": 2433
,	"vr": "40:33"
,	"pr": 1
,	"ekp": 0
,	"td": 0
,	"r1": 17
,	"r2": 19
,	"ps": 0
,	"ss": 0
,	"ish": 0
,	"pz": 0
,	gs: null
,	ob: null
,	"prg": 0
,	"ig": 122253
,	"i": "Nina"
,	"p": "JuriДЌiД‡"
}
, {
	"broj": 277997
,	"e": 2
,	"sk": 2401
,	"vr": "40:01"
,	"pr": 1
,	"ekp": 1
,	"td": 10
,	"r1": 16
,	"r2": 19
,	ps: null
,	ss: null
,	ish: null
,	pz: null
,	gs: null
,	ob: null
,	"prg": 0
,	ig: null
,	"i": ""
,	"p": ""
}
, {
	"broj": 277996
,	"e": 1
,	"sk": 2396
,	"vr": "39:56"
,	"pr": 1
,	"ekp": 0
,	"td": 0
,	"r1": 16
,	"r2": 19
,	"ps": 0
,	"ss": 0
,	"ish": 0
,	"pz": 0
,	gs: null
,	ob: null
,	"prg": 0
,	"ig": 125239
,	"i": "Victoria Eva"
,	"p": "VranjeЕЎ"
}
, {
	"broj": 277995
,	"e": 2
,	"sk": 2373
,	"vr": "39:33"
,	"pr": 1
,	"ekp": 0
,	"td": 0
,	"r1": 15
,	"r2": 19
,	"ps": 0
,	"ss": 0
,	"ish": 0
,	"pz": 0
,	gs: null
,	ob: null
,	"prg": 0
,	"ig": 124629
,	"i": "AnД‘ela"
,	"p": "SuЕЎak"
}
, {
	"broj": 277994
,	"e": 1
,	"sk": 2312
,	"vr": "38:32"
,	"pr": 1
,	"ekp": 0
,	"td": 0
,	"r1": 15
,	"r2": 18
,	"ps": 0
,	"ss": 0
,	"ish": 0
,	"pz": 0
,	gs: null
,	ob: null
,	"prg": 0
,	"ig": 125239
,	"i": "Victoria Eva"
,	"p": "VranjeЕЎ"
}
, {
	"broj": 277993
,	"e": 2
,	"sk": 2303
,	"vr": "38:23"
,	"pr": 1
,	"ekp": 0
,	"td": 0
,	"r1": 14
,	"r2": 18
,	"ps": 0
,	"ss": 0
,	"ish": 0
,	"pz": 0
,	gs: null
,	ob: null
,	"prg": 0
,	"ig": 121833
,	"i": "Petra"
,	"p": "Gustin"
}
, {
	"broj": 277992
,	"e": 1
,	"sk": 2269
,	"vr": "37:49"
,	"pr": 1
,	"ekp": 0
,	"td": 0
,	"r1": 14
,	"r2": 17
,	"ps": 0
,	"ss": 0
,	"ish": 0
,	"pz": 0
,	gs: null
,	ob: null
,	"prg": 0
,	"ig": 122253
,	"i": "Nina"
,	"p": "JuriДЌiД‡"
}
, {
	"broj": 277991
,	"e": 2
,	"sk": 2265
,	"vr": "37:45"
,	"pr": 1
,	"ekp": 0
,	"td": 0
,	"r1": 13
,	"r2": 17
,	"ps": 0
,	"ss": 0
,	"ish": 0
,	"pz": 0
,	gs: null
,	ob: null
,	"prg": 0
,	"ig": 122028
,	"i": "Martina"
,	"p": "IliД‡"
}
, {
	"broj": 277990
,	"e": 1
,	"sk": 2237
,	"vr": "37:17"
,	"pr": 1
,	"ekp": 0
,	"td": 0
,	"r1": 13
,	"r2": 16
,	"ps": 0
,	"ss": 0
,	"ish": 0
,	"pz": 0
,	gs: null
,	ob: null
,	"prg": 0
,	"ig": 127878
,	"i": "Petra"
,	"p": "Jurilj"
}
, {
	"broj": 277989
,	"e": 1
,	"sk": 2141
,	"vr": "35:41"
,	"pr": 1
,	"ekp": 0
,	"td": 0
,	"r1": 12
,	"r2": 16
,	"ps": 0
,	"ss": 0
,	"ish": 0
,	"pz": 0
,	gs: null
,	ob: null
,	"prg": 0
,	"ig": 127878
,	"i": "Petra"
,	"p": "Jurilj"
}
, {
	"broj": 277988
,	"e": 1
,	"sk": 2074
,	"vr": "34:34"
,	"pr": 1
,	"ekp": 0
,	"td": 0
,	"r1": 11
,	"r2": 16
,	"ps": 0
,	"ss": 0
,	"ish": 0
,	"pz": 0
,	gs: null
,	ob: null
,	"prg": 0
,	"ig": 127856
,	"i": "Mia"
,	"p": "Bandur"
}
, {
	"broj": 277987
,	"e": 2
,	"sk": 1944
,	"vr": "32:24"
,	"pr": 1
,	"ekp": 0
,	"td": 0
,	"r1": 10
,	"r2": 16
,	"ps": 0
,	"ss": 0
,	"ish": 0
,	"pz": 0
,	gs: null
,	ob: null
,	"prg": 0
,	"ig": 123634
,	"i": "Petra"
,	"p": "ObЕЎivaДЌ"
}
, {
	"broj": 277986
,	"e": 1
,	"sk": 1905
,	"vr": "31:45"
,	"pr": 1
,	"ekp": 0
,	"td": 4
,	"r1": 10
,	"r2": 15
,	ps: null
,	ss: null
,	ish: null
,	pz: null
,	gs: null
,	ob: null
,	"prg": 0
,	"ig": 127856
,	"i": "Mia"
,	"p": "Bandur"
}
, {
	"broj": 277985
,	"e": 1
,	"sk": 1882
,	"vr": "31:22"
,	"pr": 1
,	"ekp": 0
,	"td": 0
,	"r1": 10
,	"r2": 15
,	"ps": 0
,	"ss": 0
,	"ish": 0
,	"pz": 0
,	gs: null
,	ob: null
,	"prg": 0
,	"ig": 125239
,	"i": "Victoria Eva"
,	"p": "VranjeЕЎ"
}
, {
	"broj": 277984
,	"e": 2
,	"sk": 1870
,	"vr": "31:10"
,	"pr": 1
,	"ekp": 0
,	"td": 0
,	"r1": 9
,	"r2": 15
,	"ps": 0
,	"ss": 0
,	"ish": 0
,	"pz": 0
,	gs: null
,	ob: null
,	"prg": 0
,	"ig": 124629
,	"i": "AnД‘ela"
,	"p": "SuЕЎak"
}
, {
	"broj": 277983
,	"e": 1
,	"sk": 1788
,	"vr": "29:48"
,	"pr": 0
,	"ekp": 0
,	"td": 0
,	"r1": 9
,	"r2": 14
,	"ps": 0
,	"ss": 0
,	"ish": 0
,	"pz": 0
,	gs: null
,	ob: null
,	"prg": 0
,	"ig": 122253
,	"i": "Nina"
,	"p": "JuriДЌiД‡"
}
, {
	"broj": 277982
,	"e": 2
,	"sk": 1749
,	"vr": "29:09"
,	"pr": 0
,	"ekp": 0
,	"td": 0
,	"r1": 8
,	"r2": 14
,	"ps": 0
,	"ss": 0
,	"ish": 0
,	"pz": 0
,	gs: null
,	ob: null
,	"prg": 0
,	"ig": 128488
,	"i": "Rita"
,	"p": "Е iljeg"
}
, {
	"broj": 277981
,	"e": 2
,	"sk": 1662
,	"vr": "27:42"
,	"pr": 0
,	"ekp": 0
,	"td": 0
,	"r1": 8
,	"r2": 13
,	"ps": 0
,	"ss": 0
,	"ish": 0
,	"pz": 0
,	gs: null
,	ob: null
,	"prg": 0
,	"ig": 128488
,	"i": "Rita"
,	"p": "Е iljeg"
}
, {
	"broj": 277980
,	"e": 2
,	"sk": 1540
,	"vr": "25:40"
,	"pr": 0
,	"ekp": 0
,	"td": 0
,	"r1": 8
,	"r2": 12
,	"ps": 0
,	"ss": 0
,	"ish": 0
,	"pz": 0
,	gs: null
,	ob: null
,	"prg": 0
,	"ig": 124629
,	"i": "AnД‘ela"
,	"p": "SuЕЎak"
}
, {
	"broj": 277979
,	"e": 1
,	"sk": 1460
,	"vr": "24:20"
,	"pr": 0
,	"ekp": 0
,	"td": 0
,	"r1": 8
,	"r2": 11
,	"ps": 0
,	"ss": 0
,	"ish": 0
,	"pz": 0
,	gs: null
,	ob: null
,	"prg": 0
,	"ig": 125239
,	"i": "Victoria Eva"
,	"p": "VranjeЕЎ"
}
, {
	"broj": 277978
,	"e": 1
,	"sk": 1345
,	"vr": "22:25"
,	"pr": 0
,	"ekp": 1
,	"td": 10
,	"r1": 7
,	"r2": 11
,	ps: null
,	ss: null
,	ish: null
,	pz: null
,	gs: null
,	ob: null
,	"prg": 0
,	ig: null
,	"i": ""
,	"p": ""
}
, {
	"broj": 277977
,	"e": 2
,	"sk": 1327
,	"vr": "22:07"
,	"pr": 0
,	"ekp": 0
,	"td": 0
,	"r1": 7
,	"r2": 11
,	"ps": 0
,	"ss": 0
,	"ish": 0
,	"pz": 0
,	gs: null
,	ob: null
,	"prg": 0
,	"ig": 124629
,	"i": "AnД‘ela"
,	"p": "SuЕЎak"
}
, {
	"broj": 277976
,	"e": 1
,	"sk": 1226
,	"vr": "20:26"
,	"pr": 0
,	"ekp": 0
,	"td": 7
,	"r1": 7
,	"r2": 10
,	ps: null
,	ss: null
,	ish: null
,	pz: null
,	gs: null
,	ob: null
,	"prg": 0
,	"ig": 122253
,	"i": "Nina"
,	"p": "JuriДЌiД‡"
}
, {
	"broj": 277975
,	"e": 2
,	"sk": 1033
,	"vr": "17:13"
,	"pr": 0
,	"ekp": 0
,	"td": 0
,	"r1": 7
,	"r2": 10
,	"ps": 0
,	"ss": 0
,	"ish": 0
,	"pz": 0
,	gs: null
,	ob: null
,	"prg": 0
,	"ig": 123634
,	"i": "Petra"
,	"p": "ObЕЎivaДЌ"
}
, {
	"broj": 277974
,	"e": 2
,	"sk": 960
,	"vr": "16:00"
,	"pr": 0
,	"ekp": 0
,	"td": 0
,	"r1": 7
,	"r2": 9
,	"ps": 0
,	"ss": 0
,	"ish": 0
,	"pz": 0
,	gs: null
,	ob: null
,	"prg": 0
,	"ig": 128488
,	"i": "Rita"
,	"p": "Е iljeg"
}
, {
	"broj": 277973
,	"e": 2
,	"sk": 904
,	"vr": "15:04"
,	"pr": 0
,	"ekp": 0
,	"td": 0
,	"r1": 7
,	"r2": 8
,	"ps": 0
,	"ss": 0
,	"ish": 0
,	"pz": 0
,	gs: null
,	ob: null
,	"prg": 0
,	"ig": 123634
,	"i": "Petra"
,	"p": "ObЕЎivaДЌ"
}
, {
	"broj": 277972
,	"e": 2
,	"sk": 876
,	"vr": "14:36"
,	"pr": 0
,	"ekp": 0
,	"td": 0
,	"r1": 7
,	"r2": 7
,	"ps": 0
,	"ss": 0
,	"ish": 0
,	"pz": 0
,	gs: null
,	ob: null
,	"prg": 0
,	"ig": 125157
,	"i": "Marta"
,	"p": "VidoviД‡"
}
, {
	"broj": 277971
,	"e": 1
,	"sk": 825
,	"vr": "13:45"
,	"pr": 0
,	"ekp": 0
,	"td": 0
,	"r1": 7
,	"r2": 6
,	"ps": 0
,	"ss": 0
,	"ish": 0
,	"pz": 0
,	gs: null
,	ob: null
,	"prg": 0
,	"ig": 124383
,	"i": "AnД‘ela Kristina"
,	"p": "Selak"
}
, {
	"broj": 277970
,	"e": 1
,	"sk": 780
,	"vr": "13:00"
,	"pr": 0
,	"ekp": 0
,	"td": 0
,	"r1": 6
,	"r2": 6
,	"ps": 0
,	"ss": 0
,	"ish": 0
,	"pz": 0
,	gs: null
,	ob: null
,	"prg": 0
,	"ig": 127856
,	"i": "Mia"
,	"p": "Bandur"
}
, {
	"broj": 277969
,	"e": 2
,	"sk": 726
,	"vr": "12:06"
,	"pr": 0
,	"ekp": 0
,	"td": 0
,	"r1": 5
,	"r2": 6
,	"ps": 0
,	"ss": 0
,	"ish": 0
,	"pz": 0
,	gs: null
,	ob: null
,	"prg": 0
,	"ig": 123634
,	"i": "Petra"
,	"p": "ObЕЎivaДЌ"
}
, {
	"broj": 277968
,	"e": 2
,	"sk": 676
,	"vr": "11:16"
,	"pr": 0
,	"ekp": 0
,	"td": 0
,	"r1": 5
,	"r2": 5
,	"ps": 0
,	"ss": 0
,	"ish": 0
,	"pz": 0
,	gs: null
,	ob: null
,	"prg": 0
,	"ig": 124629
,	"i": "AnД‘ela"
,	"p": "SuЕЎak"
}
, {
	"broj": 277967
,	"e": 1
,	"sk": 629
,	"vr": "10:29"
,	"pr": 0
,	"ekp": 0
,	"td": 0
,	"r1": 5
,	"r2": 4
,	"ps": 0
,	"ss": 0
,	"ish": 0
,	"pz": 0
,	gs: null
,	ob: null
,	"prg": 0
,	"ig": 127856
,	"i": "Mia"
,	"p": "Bandur"
}
, {
	"broj": 277966
,	"e": 2
,	"sk": 614
,	"vr": "10:14"
,	"pr": 0
,	"ekp": 0
,	"td": 4
,	"r1": 4
,	"r2": 4
,	ps: null
,	ss: null
,	ish: null
,	pz: null
,	gs: null
,	ob: null
,	"prg": 0
,	"ig": 124525
,	"i": "Antonela"
,	"p": "Srna"
}
, {
	"broj": 277965
,	"e": 2
,	"sk": 607
,	"vr": "10:07"
,	"pr": 0
,	"ekp": 0
,	"td": 0
,	"r1": 4
,	"r2": 4
,	"ps": 3
,	"ss": 0
,	"ish": 1
,	"pz": 0
,	gs: null
,	ob: null
,	"prg": 0
,	"ig": 124629
,	"i": "AnД‘ela"
,	"p": "SuЕЎak"
}
, {
	"broj": 277964
,	"e": 1
,	"sk": 551
,	"vr": "9:11"
,	"pr": 0
,	"ekp": 0
,	"td": 0
,	"r1": 4
,	"r2": 4
,	"ps": 0
,	"ss": 0
,	"ish": 0
,	"pz": 0
,	gs: null
,	ob: null
,	"prg": 0
,	"ig": 124383
,	"i": "AnД‘ela Kristina"
,	"p": "Selak"
}
, {
	"broj": 277963
,	"e": 1
,	"sk": 484
,	"vr": "8:04"
,	"pr": 0
,	"ekp": 0
,	"td": 0
,	"r1": 3
,	"r2": 4
,	"ps": 0
,	"ss": 0
,	"ish": 0
,	"pz": 0
,	gs: null
,	ob: null
,	"prg": 0
,	"ig": 127856
,	"i": "Mia"
,	"p": "Bandur"
}
, {
	"broj": 277962
,	"e": 1
,	"sk": 446
,	"vr": "7:26"
,	"pr": 0
,	"ekp": 0
,	"td": 0
,	"r1": 2
,	"r2": 4
,	"ps": 0
,	"ss": 0
,	"ish": 0
,	"pz": 0
,	gs: null
,	ob: null
,	"prg": 0
,	"ig": 124383
,	"i": "AnД‘ela Kristina"
,	"p": "Selak"
}
, {
	"broj": 277961
,	"e": 2
,	"sk": 385
,	"vr": "6:25"
,	"pr": 0
,	"ekp": 0
,	"td": 0
,	"r1": 1
,	"r2": 4
,	"ps": 0
,	"ss": 0
,	"ish": 0
,	"pz": 0
,	gs: null
,	ob: null
,	"prg": 0
,	"ig": 124629
,	"i": "AnД‘ela"
,	"p": "SuЕЎak"
}
, {
	"broj": 277960
,	"e": 1
,	"sk": 370
,	"vr": "6:10"
,	"pr": 0
,	"ekp": 0
,	"td": 7
,	"r1": 1
,	"r2": 3
,	ps: null
,	ss: null
,	ish: null
,	pz: null
,	gs: null
,	ob: null
,	"prg": 0
,	"ig": 124383
,	"i": "AnД‘ela Kristina"
,	"p": "Selak"
}
, {
	"broj": 277959
,	"e": 1
,	"sk": 330
,	"vr": "5:30"
,	"pr": 0
,	"ekp": 0
,	"td": 0
,	"r1": 1
,	"r2": 3
,	"ps": 0
,	"ss": 0
,	"ish": 0
,	"pz": 0
,	gs: null
,	ob: null
,	"prg": 0
,	"ig": 127856
,	"i": "Mia"
,	"p": "Bandur"
}
, {
	"broj": 277958
,	"e": 2
,	"sk": 209
,	"vr": "3:29"
,	"pr": 0
,	"ekp": 0
,	"td": 0
,	"r1": 0
,	"r2": 3
,	"ps": 0
,	"ss": 0
,	"ish": 0
,	"pz": 0
,	gs: null
,	ob: null
,	"prg": 0
,	"ig": 126504
,	"i": "Lucija"
,	"p": "DruЕѕijaniД‡"
}
, {
	"broj": 277957
,	"e": 2
,	"sk": 68
,	"vr": "1:08"
,	"pr": 0
,	"ekp": 0
,	"td": 0
,	"r1": 0
,	"r2": 2
,	"ps": 0
,	"ss": 0
,	"ish": 0
,	"pz": 0
,	gs: null
,	ob: null
,	"prg": 0
,	"ig": 124629
,	"i": "AnД‘ela"
,	"p": "SuЕЎak"
}
, {
	"broj": 277956
,	"e": 2
,	"sk": 53
,	"vr": "0:53"
,	"pr": 0
,	"ekp": 0
,	"td": 7
,	"r1": 0
,	"r2": 1
,	ps: null
,	ss: null
,	ish: null
,	pz: null
,	gs: null
,	ob: null
,	"prg": 0
,	"ig": 124525
,	"i": "Antonela"
,	"p": "Srna"
}
, {
	"broj": 277955
,	"e": 2
,	"sk": 39
,	"vr": "0:39"
,	"pr": 0
,	"ekp": 0
,	"td": 0
,	"r1": 0
,	"r2": 1
,	"ps": 0
,	"ss": 0
,	"ish": 0
,	"pz": 0
,	gs: null
,	ob: null
,	"prg": 0
,	"ig": 124629
,	"i": "AnД‘ela"
,	"p": "SuЕЎak"
}
]
, sudionici: [
{
	"broj": 148429
,	"izvor": 567
,	"tip": 3
,	"rbtip": 1
,	"igrac": 119713
,	detaljno: null
,	"oznaka": ""
,	"i": "Stipe"
,	"p": "Torbarina"
}
, {
	"broj": 148430
,	"izvor": 567
,	"tip": 3
,	"rbtip": 2
,	"igrac": 119712
,	detaljno: null
,	"oznaka": ""
,	"i": "Е ime"
,	"p": "Torbarina"
}
, {
	"broj": 148431
,	"izvor": 567
,	"tip": 4
,	rbtip: null
,	"igrac": 119817
,	"detaljno": 0
,	"oznaka": ""
,	"i": "Dragan"
,	"p": "Kaleb"
}
, {
	"broj": 148432
,	"izvor": 567
,	"tip": 4
,	rbtip: null
,	"igrac": 119534
,	"detaljno": 2
,	"oznaka": ""
,	"i": "Ante"
,	"p": "MandiД‡"
}
, {
	"broj": 148433
,	"izvor": 567
,	"tip": 4
,	rbtip: null
,	"igrac": 119532
,	"detaljno": 1
,	"oznaka": ""
,	"i": "AnД‘ela"
,	"p": "MaloДЌa"
}
, {
	"broj": 148434
,	"izvor": 567
,	"tip": 5
,	rbtip: null
,	"igrac": 127870
,	"detaljno": 2
,	"oznaka": ""
,	"i": "Marin"
,	"p": "Ivanac"
}
, {
	"broj": 148435
,	"izvor": 567
,	"tip": 5
,	rbtip: null
,	"igrac": 137876
,	"detaljno": 1
,	"oznaka": ""
,	"i": "ЕЅeljka"
,	"p": "Radalj"
}
, {
	"broj": 148436
,	"izvor": 567
,	"tip": 1
,	rbtip: null
,	"igrac": 122818
,	detaljno: null
,	"oznaka": "B"
,	"i": "Leona"
,	"p": "LendiД‡ KovaДЌeviД‡"
}
, {
	"broj": 148437
,	"izvor": 567
,	"tip": 2
,	rbtip: null
,	"igrac": 123270
,	detaljno: null
,	"oznaka": "A"
,	"i": "Tina"
,	"p": "MeД‘ureДЌan"
}
, {
	"broj": 148438
,	"izvor": 567
,	"tip": 1
,	rbtip: null
,	"igrac": 135007
,	detaljno: null
,	"oznaka": "B"
,	"i": "Mariela"
,	"p": "KriЕѕanoviД‡"
}
, {
	"broj": 148439
,	"izvor": 567
,	"tip": 2
,	rbtip: null
,	"igrac": 122480
,	detaljno: null
,	"oznaka": "A"
,	"i": "Tomislav"
,	"p": "Komazin"
}
, {
	"broj": 148440
,	"izvor": 567
,	"tip": 2
,	rbtip: null
,	"igrac": 136681
,	detaljno: null
,	"oznaka": "C"
,	"i": "BlaЕѕ"
,	"p": "KriЕѕanoviД‡"
}
]
, dokumenti: [
]
}
